---

- include: create_swap_file.yml
  when: create_swap_file
  tags: swap

- name: Ensure bash, OpenSSl, and libssl are the latest versions
  apt: name={{ item }} update_cache={{ update_apt_cache }} state=latest
  with_items:
    - bash
    - openssl
    - libssl-dev
    - libssl-doc
  tags: packages

- name: Install base packages
  apt: name={{ item }} update_cache={{ update_apt_cache }} force=yes state=present
  with_items:
    - build-essential
    - ntp
    - htop
    - git
    - bc
    - python3-dev
    - python3-pip
    - python3-pycurl
    - python3-venv
    - software-properties-common
    - supervisor
    - sudo
  tags: packages

- name: Start supervisor
  service: name=supervisor state=started enabled=yes

- name: Install virtualenv
  pip: name=virtualenv executable=pip3
  tags: packages

- include: setup_py37.yml

- include: setup_ufw.yml
  when: setup_ufw
  tags: ufw
