---

- include: create_users_and_groups.yml

- include: setup_virtualenv.yml

- include: setup_git_repo.yml

- include: setup_dotenv.yml

- include: setup_django_app.yml

- include: setup_supervisor.yml

- include: set_file_permissions.yml

- include: setup_nginx.yml

- include: setup_le.yml
  when: setup_lets_encrypt == 'yes'
